# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~ BIOSTAT 907 Term Project R Code ~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# ~~~~~~~ Plotting Trends of RR Boundary with FS ~~~~~~~~~~~~~~~

# Author: Yi Liu
# Create date: 09/26/2021

# This script can generate plot of a1/n1 - P0 vs P0 and a/n - P vs P0
# and frequency plot of a1 - n1*P0 vs P0 and a - n*P vs P0
# to investigate the RR testing boundary given different design settings

library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(xtable)

# Data generated by "data_FS.R"
load("design_FS.rdata")


# Plotting function
freq.fig.FS <- function(dataset) {
  
  op.dat <- dataset$op.design %>% mutate(design = "optimal")
  mm.dat <- dataset$mm.design %>% mutate(design = "minimax")
  
  fig.data <- rbind(op.dat, mm.dat) %>% select(p0, p1, a1, N1, a, N, design)
  
  p1 <- ggplot(fig.data, aes(x=p0, y=a1-N1*p0, col=design)) + geom_line(size=0.5) + 
    labs(x=expression(p[0]), y=expression(paste(a[1],"-",n[1]*p[0]),sep=" ")) + 
    scale_color_manual(values = c("steelblue", "darkorange")) + 
    ylim(-3, 3) + geom_abline(slope = 0, col="olivedrab") +
    theme_bw() + theme(legend.position = "n")
  
  p2 <- ggplot(fig.data, aes(x=p0, y=a-(p0+p1)*N/2, col=design)) + geom_line(size=0.5) + 
    labs(x=expression(p[0]), y=expression(paste(a, "-", n*(p[0]+p[1])/2, sep=" ")))  + 
    scale_color_manual(values = c("steelblue", "darkorange")) + 
    ylim(-3, 3) + geom_abline(slope = 0, col="olivedrab") +
    theme_bw()
  
  grid.arrange(p1, p2, ncol=2, widths=c(6,9), heights = 1,
               top=textGrob(paste("RR Critical Values (in Frequency)", 
                                  "with futility stopping only", sep = "\n")))
}


SumStat.FS <- function(dataset) {
  
  op.dat <- dataset$op.design
  mm.dat <- dataset$mm.design
  
  # Frequency
  f1.op <- summary(op.dat[, "a1"] - op.dat[, "N1"] * op.dat$p0) %>% as.numeric()
  fsd1.op <- sd(op.dat[, "a1"] - op.dat[, "N1"] * op.dat$p0)
  fIQR1.op <- IQR(op.dat[, "a1"] - op.dat[, "N1"] * op.dat$p0)
  f1.mm <- summary(mm.dat[, "a1"] - mm.dat[, "N1"] * mm.dat$p0) %>% as.numeric()
  fsd1.mm <- sd(mm.dat[, "a1"] - mm.dat[, "N1"] * mm.dat$p0)
  fIQR1.mm <- IQR(mm.dat[, "a1"] - mm.dat[, "N1"] * mm.dat$p0)
  
  f2.op <- summary(op.dat[, "a"] - op.dat[, "N"] * (op.dat$p0 + op.dat$p1)/2) %>% as.numeric()
  fsd2.op <- sd(op.dat[, "a"] - op.dat[, "N"] * (op.dat$p0 + op.dat$p1)/2)
  fIQR2.op <- IQR(op.dat[, "a"] - op.dat[, "N"] * (op.dat$p0 + op.dat$p1)/2)
  f2.mm <- summary(mm.dat[, "a"] - mm.dat[, "N"] * (mm.dat$p0 + mm.dat$p1)/2) %>% as.numeric()
  fsd2.mm <- sd(mm.dat[, "a"] - mm.dat[, "N"] * (mm.dat$p0 + mm.dat$p1)/2)
  fIQR2.mm <- IQR(mm.dat[, "a"] - mm.dat[, "N"] * (mm.dat$p0 + mm.dat$p1)/2)
  
  Freq <- data.frame(
    Stage = c("Stage 1", "", "Stage 2", ""),
    Design = c("Optimal", "Minimax", "Optimal", "Minimax"),
    Median = c(f1.op[3], f1.mm[3], f2.op[3], f2.mm[3]),
    Mean = c(f1.op[4], f1.mm[4], f2.op[4], f2.mm[4]),
    IQR = c(fIQR1.op, fIQR1.mm, fIQR2.op, fIQR2.mm),
    SD = c(fsd1.op, fsd1.mm, fsd2.op, fsd2.mm)
  )
  
  return(Freq = Freq)
  
}


# Results
path <- paste(here::here(),"/Slides",sep="")

#### 0.8, 0.1
setEPS()
postscript(paste(path,"/FS1.eps",sep=""),width=6,height=2.5)
freq.fig.FS(dataset = ls1.1)
dev.off()

f.table <- SumStat.FS(dataset = ls1.1)
xtable(f.table, digits=3)


#### 0.8, 0.05
setEPS()
postscript(paste(path,"/FS2.eps",sep=""),width=6,height=2.5)
freq.fig.FS(dataset = ls4.1)
dev.off()

f.table <- SumStat.FS(dataset = ls4.1)
xtable(f.table, digits=3)


#### 0.9, 0.1
setEPS()
postscript(paste(path,"/FS3.eps",sep=""),width=6,height=2.5)
freq.fig.FS(dataset = ls3.1)
dev.off()

f.table <- SumStat.FS(dataset = ls3.1)
xtable(f.table, digits=3)


#### 0.9, 0.05
setEPS()
postscript(paste(path,"/FS4.eps",sep=""),width=6,height=2.5)
freq.fig.FS(dataset = ls6.1)
dev.off()

f.table <- SumStat.FS(dataset = ls6.1)
xtable(f.table, digits=3)











