# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~ BIOSTAT 907 Term Project R Code ~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# ~~~~~~~ Plotting Trends of RR Boundary with two S ~~~~~~~~~~~~

# Author: Yi Liu
# Create date: 10/21/2021

# This script can generate plot of a1/n1 - P0 vs P0, b1/n1 - P1 vs P0, and a/n - P vs P0
# and frequency plot of a1 - n1*P0 vs P0, b1 - n1*P1 vs P0 and a - n*P vs P0
# to investigate the RR testing boundary given different design settings

library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(xtable)

# Data generated by "data_twoS.R"
load("design_twoS.rdata")



freq.fig.twoS <- function(dataset) {
  
  op.dat <- dataset$op.design %>% mutate(design = "optimal")
  mm.dat <- dataset$mm.design %>% mutate(design = "minimax")
  
  fig.data <- rbind(op.dat, mm.dat) %>% select(p0, p1, a1, b1, N1, a, b, N, design)
  
  p1 <- ggplot(fig.data, aes(x=p0, y=a1-N1*p0, col=design)) + geom_line(size=0.5) + 
    labs(x=expression(p[0]), y=expression(paste(a[1],"-",n[1]*p[0]))) + 
    scale_color_manual(values = c("steelblue", "darkorange")) + 
    ylim(-3, 3) + geom_abline(slope = 0, col="olivedrab") +
    theme_bw() + theme(legend.position = "n")
  
  p2 <- ggplot(fig.data, aes(x=p0, y=b1-N1*p1, col=design)) + geom_line(size=0.5) + 
    labs(x=expression(p[0]), y=expression(paste(b[1],"-",n[1]*p[1])))  + 
    scale_color_manual(values = c("steelblue", "darkorange")) + 
    ylim(-3, 3) + geom_abline(slope = 0, col="olivedrab") +
    theme_bw() + theme(legend.position = "n")
  
  p3 <- ggplot(fig.data, aes(x=p0, y=a-(p0+p1)*N/2, col=design)) + geom_line(size=0.5) + 
    labs(x=expression(p[0]), y=expression(paste(a,"-",n*(p[0]+p[1])/2)))  + 
    scale_color_manual(values = c("steelblue", "darkorange")) + 
    ylim(-3, 3) + geom_abline(slope = 0, col="olivedrab") +
    theme_bw()
  
  grid.arrange(p1, p2, p3, ncol=3, widths=c(3,3,4),
               top=textGrob(paste("RR Critical Values (in Frequency)", 
                                  "with both futility and superiority stoppings", sep = "\n")))
}


SumStat.twoS <- function(dataset) {
  
  op.dat <- dataset$op.design
  mm.dat <- dataset$mm.design
  
  
  # Frequency
  f1.op <- summary(op.dat[, "a1"] - op.dat[, "N1"] * op.dat$p0) %>% as.numeric()
  fsd1.op <- sd(op.dat[, "a1"] - op.dat[, "N1"] * op.dat$p0)
  fIQR1.op <- IQR(op.dat[, "a1"] - op.dat[, "N1"] * op.dat$p0)
  f1.mm <- summary(mm.dat[, "a1"] - mm.dat[, "N1"] * mm.dat$p0) %>% as.numeric()
  fsd1.mm <- sd(mm.dat[, "a1"] - mm.dat[, "N1"] * mm.dat$p0)
  fIQR1.mm <- IQR(mm.dat[, "a1"] - mm.dat[, "N1"] * mm.dat$p0)
  
  f2.op <- summary(op.dat[, "b1"] - op.dat[, "N1"] * op.dat$p1) %>% as.numeric()
  fsd2.op <- sd(op.dat[, "b1"] - op.dat[, "N1"] * op.dat$p1)
  fIQR2.op <- IQR(op.dat[, "b1"] - op.dat[, "N1"] * op.dat$p1)
  f2.mm <- summary(mm.dat[, "b1"] - mm.dat[, "N1"] * mm.dat$p1) %>% as.numeric()
  fsd2.mm <- sd(mm.dat[, "b1"] - mm.dat[, "N1"] * mm.dat$p1)
  fIQR2.mm <- IQR(mm.dat[, "b1"] - mm.dat[, "N1"] * mm.dat$p1)
  
  f3.op <- summary(op.dat[, "a"] - op.dat[, "N"] * (op.dat$p0 + op.dat$p1)/2) %>% as.numeric()
  fsd3.op <- sd(op.dat[, "a"] - op.dat[, "N"] * (op.dat$p0 + op.dat$p1)/2)
  fIQR3.op <- IQR(op.dat[, "a"] - op.dat[, "N"] * (op.dat$p0 + op.dat$p1)/2)
  f3.mm <- summary(mm.dat[, "a"] - mm.dat[, "N"] * (mm.dat$p0 + mm.dat$p1)/2) %>% as.numeric()
  fsd3.mm <- sd(mm.dat[, "a"] - mm.dat[, "N"] * (mm.dat$p0 + mm.dat$p1)/2)
  fIQR3.mm <- IQR(mm.dat[, "a"] - mm.dat[, "N"] * (mm.dat$p0 + mm.dat$p1)/2)
  
  Freq <- data.frame(
    Stage = c("Stage 1 Lower", "", "Stage 1 Upper", "", "Stage 2 Lower", ""),
    Design = c("Optimal", "Minimax", "Optimal", "Minimax", "Optimal", "Minimax"),
    Median = c(f1.op[3], f1.mm[3], f2.op[3], f2.mm[3], f3.op[3], f3.mm[3]),
    Mean = c(f1.op[4], f1.mm[4], f2.op[4], f2.mm[4], f3.op[4], f3.mm[4]),
    IQR = c(fIQR1.op, fIQR1.mm, fIQR2.op, fIQR2.mm, fIQR3.op, fIQR3.mm),
    SD = c(fsd1.op, fsd1.mm, fsd2.op, fsd2.mm, fsd3.op, fsd3.mm)
  )
  
  return(Freq = Freq)
  
}

# Results
path <- paste(here::here(),"/Slides",sep="")

#### 0.8, 0.1
setEPS()
postscript(paste(path,"/twoS1.eps",sep=""),width=9.5,height=2.5)
freq.fig.twoS(dataset = ls1.1)
dev.off()

f.table <- SumStat.twoS(dataset = ls1.1)
xtable(f.table, digits=3)

#### 0.8, 0.05
setEPS()
postscript(paste(path,"/twoS2.eps",sep=""),width=9.5,height=2.5)
freq.fig.twoS(dataset = ls4.1)
dev.off()

f.table <- SumStat.twoS(dataset = ls4.1)
xtable(f.table, digits=3)

#### 0.9, 0.1
setEPS()
postscript(paste(path,"/twoS3.eps",sep=""),width=9.5,height=2.5)
freq.fig.twoS(dataset = ls3.1)
dev.off()

f.table <- SumStat.twoS(dataset = ls3.1)
xtable(f.table, digits=3)


#### 0.9, 0.05
setEPS()
postscript(paste(path,"/twoS4.eps",sep=""),width=9.5,height=2.5)
freq.fig.twoS(dataset = ls6.1)
dev.off()

f.table <- SumStat.twoS(dataset = ls6.1)
xtable(f.table, digits=3)




